/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resistencia;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author wolfm
 */
public class Interfaz extends javax.swing.JFrame {
String cad1;
String cad2;
String cad3;

    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pantalla1 = new javax.swing.JTextField();
        Bandas4d = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        Calcular4Bandas = new javax.swing.JButton();
        Bandas4b = new javax.swing.JButton();
        Bandas4a = new javax.swing.JButton();
        Bandas4c = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Bandas5e = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Bandas5a = new javax.swing.JButton();
        Bandas6d = new javax.swing.JButton();
        Bandas5b = new javax.swing.JButton();
        Bandas5d = new javax.swing.JButton();
        Bandas5c = new javax.swing.JButton();
        Bandas6a = new javax.swing.JButton();
        Bandas6b = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Bandas6e = new javax.swing.JButton();
        Bandas6f = new javax.swing.JButton();
        Bandas6c = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Pantalla2 = new javax.swing.JTextField();
        Pantalla3 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        Calcular6Bandas = new javax.swing.JButton();
        Calcular5Bandas = new javax.swing.JButton();
        Multi3 = new javax.swing.JComboBox<>();
        Multi1 = new javax.swing.JComboBox<>();
        Multi2 = new javax.swing.JComboBox<>();
        Tolerancia3 = new javax.swing.JComboBox<>();
        Tolerancia1 = new javax.swing.JComboBox<>();
        Tolerancia2 = new javax.swing.JComboBox<>();
        Temperatura = new javax.swing.JComboBox<>();
        ColoresSelec = new javax.swing.JComboBox<>();
        Principal = new javax.swing.JTextField();
        ImpCad6Band = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        ImpCad4Band = new javax.swing.JButton();
        ImpCad5Band = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Pantalla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pantalla1ActionPerformed(evt);
            }
        });
        getContentPane().add(Pantalla1);
        Pantalla1.setBounds(20, 70, 90, 43);

        Bandas4d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bandas4dActionPerformed(evt);
            }
        });
        getContentPane().add(Bandas4d);
        Bandas4d.setBounds(280, 180, 40, 80);

        jTextField2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTextField2.setText("Ohms");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(1280, 70, 63, 43);

        Calcular4Bandas.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Calcular4Bandas.setText("Calcular colores");
        Calcular4Bandas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calcular4BandasActionPerformed(evt);
            }
        });
        getContentPane().add(Calcular4Bandas);
        Calcular4Bandas.setBounds(140, 130, 180, 38);

        Bandas4b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bandas4bActionPerformed(evt);
            }
        });
        getContentPane().add(Bandas4b);
        Bandas4b.setBounds(170, 180, 40, 80);

        Bandas4a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bandas4aActionPerformed(evt);
            }
        });
        getContentPane().add(Bandas4a);
        Bandas4a.setBounds(110, 180, 40, 80);

        Bandas4c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bandas4cActionPerformed(evt);
            }
        });
        getContentPane().add(Bandas4c);
        Bandas4c.setBounds(220, 180, 40, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Resistencia34.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(700, 393));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 180, 309, 82);

        Bandas5e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bandas5eActionPerformed(evt);
            }
        });
        getContentPane().add(Bandas5e);
        Bandas5e.setBounds(720, 190, 20, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Resistencia34.jpg"))); // NOI18N
        jLabel2.setText("jLabel1");
        jLabel2.setPreferredSize(new java.awt.Dimension(700, 393));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 180, 309, 82);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Resistencia34.jpg"))); // NOI18N
        jLabel3.setText("jLabel1");
        jLabel3.setPreferredSize(new java.awt.Dimension(700, 393));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 180, 309, 82);

        Bandas5a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bandas5aActionPerformed(evt);
            }
        });
        getContentPane().add(Bandas5a);
        Bandas5a.setBounds(560, 190, 20, 80);

        Bandas6d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bandas6dActionPerformed(evt);
            }
        });
        getContentPane().add(Bandas6d);
        Bandas6d.setBounds(1090, 190, 20, 80);

        Bandas5b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bandas5bActionPerformed(evt);
            }
        });
        getContentPane().add(Bandas5b);
        Bandas5b.setBounds(600, 190, 20, 80);

        Bandas5d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bandas5dActionPerformed(evt);
            }
        });
        getContentPane().add(Bandas5d);
        Bandas5d.setBounds(680, 190, 20, 80);

        Bandas5c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bandas5cActionPerformed(evt);
            }
        });
        getContentPane().add(Bandas5c);
        Bandas5c.setBounds(640, 190, 20, 80);

        Bandas6a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bandas6aActionPerformed(evt);
            }
        });
        getContentPane().add(Bandas6a);
        Bandas6a.setBounds(970, 190, 20, 80);

        Bandas6b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bandas6bActionPerformed(evt);
            }
        });
        getContentPane().add(Bandas6b);
        Bandas6b.setBounds(1010, 190, 20, 80);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Resistencia34.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(490, 190, 309, 82);

        Bandas6e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bandas6eActionPerformed(evt);
            }
        });
        getContentPane().add(Bandas6e);
        Bandas6e.setBounds(1130, 190, 20, 80);

        Bandas6f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bandas6fActionPerformed(evt);
            }
        });
        getContentPane().add(Bandas6f);
        Bandas6f.setBounds(1170, 190, 20, 80);

        Bandas6c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bandas6cActionPerformed(evt);
            }
        });
        getContentPane().add(Bandas6c);
        Bandas6c.setBounds(1050, 190, 20, 80);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Resistencia34.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(930, 190, 309, 82);

        Pantalla2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pantalla2ActionPerformed(evt);
            }
        });
        getContentPane().add(Pantalla2);
        Pantalla2.setBounds(460, 70, 110, 43);

        Pantalla3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pantalla3ActionPerformed(evt);
            }
        });
        getContentPane().add(Pantalla3);
        Pantalla3.setBounds(890, 70, 90, 43);

        jTextField3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTextField3.setText("Ohms");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(320, 70, 63, 43);

        jTextField4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTextField4.setText("Ohms");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(770, 70, 63, 43);

        Calcular6Bandas.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Calcular6Bandas.setText("Calcular colores");
        Calcular6Bandas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calcular6BandasActionPerformed(evt);
            }
        });
        getContentPane().add(Calcular6Bandas);
        Calcular6Bandas.setBounds(1040, 130, 160, 40);

        Calcular5Bandas.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Calcular5Bandas.setText("Calcular colores");
        Calcular5Bandas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calcular5BandasActionPerformed(evt);
            }
        });
        getContentPane().add(Calcular5Bandas);
        Calcular5Bandas.setBounds(570, 130, 170, 40);

        Multi3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Multi3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "x 10 ^ (0)", "x 10 ^ (1)", "x 10 ^ (2)", "x 10 ^ (3)", "x 10 ^ (4)", "x 10 ^ (5)", "x 10 ^ (6)", "x 10 ^ (7)", "x 10 ^ (8)", "x 10 ^ (9)", "x 10 ^ (-1)", "x 10 ^ (-2)" }));
        Multi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Multi3ActionPerformed(evt);
            }
        });
        getContentPane().add(Multi3);
        Multi3.setBounds(980, 70, 100, 40);

        Multi1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Multi1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "x 10 ^ (0)", "x 10 ^ (1)", "x 10 ^ (2)", "x 10 ^ (3)", "x 10 ^ (4)", "x 10 ^ (5)", "x 10 ^ (6)", "x 10 ^ (7)", "x 10 ^ (8)", "x 10 ^ (9)", "x 10 ^ (-1)", "x 10 ^ (-2)" }));
        Multi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Multi1ActionPerformed(evt);
            }
        });
        getContentPane().add(Multi1);
        Multi1.setBounds(110, 70, 100, 40);

        Multi2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Multi2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "x 10 ^ (0)", "x 10 ^ (1)", "x 10 ^ (2)", "x 10 ^ (3)", "x 10 ^ (4)", "x 10 ^ (5)", "x 10 ^ (6)", "x 10 ^ (7)", "x 10 ^ (8)", "x 10 ^ (9)", "x 10 ^ (-1)", "x 10 ^ (-2)" }));
        Multi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Multi2ActionPerformed(evt);
            }
        });
        getContentPane().add(Multi2);
        Multi2.setBounds(580, 70, 100, 40);

        Tolerancia3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Tolerancia3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "±1%", "±2%", "±0.5%", "±0.25%", "±.10%", "±.05%", "±5%", "±10%" }));
        getContentPane().add(Tolerancia3);
        Tolerancia3.setBounds(1080, 70, 90, 40);

        Tolerancia1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Tolerancia1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "±1%", "±2%", "±0.5%", "±0.25%", "±.10%", "±.05%", "±5%", "±10%" }));
        getContentPane().add(Tolerancia1);
        Tolerancia1.setBounds(220, 70, 90, 40);

        Tolerancia2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Tolerancia2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "±1%", "±2%", "±0.5%", "±0.25%", "±.10%", "±.05%", "±5%", "±10%" }));
        getContentPane().add(Tolerancia2);
        Tolerancia2.setBounds(680, 70, 90, 40);

        Temperatura.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Temperatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100 PPM/C", "50 PPM/C", "15 PPM/C", "10 PPM/C", "5 PPM/C" }));
        Temperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemperaturaActionPerformed(evt);
            }
        });
        getContentPane().add(Temperatura);
        Temperatura.setBounds(1170, 70, 110, 40);

        ColoresSelec.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        ColoresSelec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Cafe", "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Violeta", "Gris ", "Blanco", "Oro", "Plata" }));
        getContentPane().add(ColoresSelec);
        ColoresSelec.setBounds(580, 350, 200, 70);

        Principal.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        getContentPane().add(Principal);
        Principal.setBounds(470, 440, 510, 60);

        ImpCad6Band.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ImpCad6Band.setText("Calcular valor");
        ImpCad6Band.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImpCad6BandActionPerformed(evt);
            }
        });
        getContentPane().add(ImpCad6Band);
        ImpCad6Band.setBounds(1050, 290, 140, 50);

        jTextField1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jTextField1.setText("Valor de la resistencia:");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(220, 450, 230, 40);

        ImpCad4Band.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ImpCad4Band.setText("Calcular valor");
        ImpCad4Band.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImpCad4BandActionPerformed(evt);
            }
        });
        getContentPane().add(ImpCad4Band);
        ImpCad4Band.setBounds(140, 280, 140, 50);

        ImpCad5Band.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ImpCad5Band.setText("Calcular valor");
        ImpCad5Band.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImpCad5BandActionPerformed(evt);
            }
        });
        getContentPane().add(ImpCad5Band);
        ImpCad5Band.setBounds(580, 290, 140, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1350, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void Pantalla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pantalla1ActionPerformed
      
    }//GEN-LAST:event_Pantalla1ActionPerformed
     String cadena1="";
     String cadena2="";
     String cadena3="";
     String cadena4="";
     String cadena5="";
     String cadena6="";
       Color cafe=new Color(45, 25, 13);  //Creación del color café
       Color violeta=new Color(128, 0, 128);  // Creación del color violeta
       Color oro=new Color(100, 75, 0);     //Creación del color oro
       Color plata=new Color(54, 58, 59);     //Creación del color oro
     
    private void Calcular4BandasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calcular4BandasActionPerformed
      cad1= Pantalla1.getText();
      int n;
       Color cafe=new Color(45, 25, 13);  //Creación del color café
       Color violeta=new Color(128, 0, 128);  // Creación del color violeta
       Color oro=new Color(100, 75, 0);     //Creación del color oro
       Color plata=new Color(54, 58, 59);     //Creación del color oro
       for (n=0; n<=1; n++) {
        char c = cad1.charAt (n);
        if(n==0){   //Si es la primera Banda
        if(c=='0'){
        Bandas4a.setBackground(Color.BLACK);
        }
        if(c=='1'){       
    
        Bandas4a.setBackground(cafe);
        Bandas4a.setOpaque(true);
        }
        if (c=='2'){
        Bandas4a.setBackground(Color.RED);
        }
        if(c=='3'){
        Bandas4a.setBackground(Color.ORANGE);
        }
        if(c=='4'){
        Bandas4a.setBackground(Color.YELLOW);
        }
        if(c=='5'){
        Bandas4a.setBackground(Color.GREEN);    
        }
        if(c=='6'){
        Bandas4a.setBackground(Color.BLUE);    
        }
        if(c=='7'){
        Bandas4a.setBackground(violeta);
        Bandas4a.setOpaque(true);
        }
        if(c=='8'){
        Bandas4a.setBackground(Color.GRAY);
        }
        if(c=='9'){
        Bandas4a.setBackground(Color.WHITE);  
        }
        }
        
        if(n==1){           //Si es la segunda Banda
        if(c=='0'){
        Bandas4b.setBackground(Color.BLACK);
        }
        if(c=='1'){       
    
        Bandas4b.setBackground(cafe);
        Bandas4b.setOpaque(true);
        }
        if (c=='2'){
        Bandas4b.setBackground(Color.RED);
        }
        if(c=='3'){
        Bandas4b.setBackground(Color.ORANGE);
        }
        if(c=='4'){
        Bandas4b.setBackground(Color.YELLOW);
        }
        if(c=='5'){
        Bandas4b.setBackground(Color.GREEN);    
        }
        if(c=='6'){
        Bandas4b.setBackground(Color.BLUE);    
        }
        if(c=='7'){
        Bandas4b.setBackground(violeta);
        Bandas4b.setOpaque(true);
        }
        if(c=='8'){
        Bandas4b.setBackground(Color.GRAY);
        }
        if(c=='9'){
        Bandas4b.setBackground(Color.WHITE);  
        }
        }
       }
       
       // CASO Tercera Banda
      String multiplicador1 = Multi1.getSelectedItem().toString();
      if(multiplicador1=="x 10 ^ (0)"){
      Bandas4c.setBackground(Color.BLACK);
      }
      if(multiplicador1=="x 10 ^ (1)"){
      Bandas4c.setBackground(cafe);
      Bandas4c.setOpaque(true);
      }
      if(multiplicador1=="x 10 ^ (2)"){
      Bandas4c.setBackground(Color.RED);
      }
      if(multiplicador1=="x 10 ^ (3)"){
      Bandas4c.setBackground(Color.ORANGE);
      }
      if(multiplicador1=="x 10 ^ (4)"){
      Bandas4c.setBackground(Color.YELLOW);
      }
      if(multiplicador1=="x 10 ^ (5)"){
      Bandas4c.setBackground(Color.GREEN);
      }
      if(multiplicador1=="x 10 ^ (6)"){
      Bandas4c.setBackground(Color.BLUE);
      }
      if(multiplicador1=="x 10 ^ (7)"){
      Bandas4c.setBackground(violeta);
      Bandas4c.setOpaque(true);
      }
      if(multiplicador1=="x 10 ^ (8)"){
      Bandas4c.setBackground(Color.GRAY);
      }
      if(multiplicador1=="x 10 ^ (9)"){
      Bandas4c.setBackground(Color.WHITE);
      }
      if(multiplicador1=="x 10 ^ (-1)"){
      Bandas4c.setBackground(oro);
      Bandas4c.setOpaque(true);
      }
      if(multiplicador1=="x 10 ^ (-2)"){
      Bandas4c.setBackground(plata);
      Bandas4c.setOpaque(true);
      }
    //CASO CUARTA BANDA
     String tole = Tolerancia1.getSelectedItem().toString();
     if(tole=="±1%"){
     Bandas4d.setBackground(cafe);
     Bandas4d.setOpaque(true);}
     if(tole=="±2%"){
     Bandas4d.setBackground(Color.RED);
     }
     if(tole=="±0.5%"){
     Bandas4d.setBackground(Color.GREEN);
     }
     if(tole=="±0.25%"){
     Bandas4d.setBackground(Color.BLUE);
     }
     if(tole=="±0.10%"){
     Bandas4d.setBackground(violeta);
     Bandas4c.setOpaque(true);
     }
     if(tole=="±0.05%"){
     Bandas4d.setBackground(Color.GRAY);
     }
     if(tole=="±5%"){
     Bandas4d.setBackground(oro);
     Bandas4c.setOpaque(true);
     }
     if(tole=="±10%"){
     Bandas4d.setBackground(plata);
     Bandas4c.setOpaque(true);
     }
    }//GEN-LAST:event_Calcular4BandasActionPerformed

    private void Bandas5eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bandas5eActionPerformed
           String color = ColoresSelec.getSelectedItem().toString();
        if(color=="Negro"){
            Principal.setText("Color no valido, eliga otro");
        }
        if(color=="Cafe"){
        cadena5 ="±1%";
        Bandas5e.setBackground(cafe);
        }
        if(color=="Rojo"){
        cadena5 ="±2%";
        Bandas5e.setBackground(Color.RED);
        }
        if(color=="Naranja"){
        Principal.setText("Color no valido, eliga otro");
        }
        if(color=="Amarillo"){
        Principal.setText("Color no valido, eliga otro");
        }
        if(color=="Verde"){
        cadena5 ="±0.5%";
        Bandas5e.setBackground(Color.GREEN);
        }   
        if(color=="Azul"){
        cadena5 ="±0.25%";
        Bandas5e.setBackground(Color.BLUE);
        }  
        if(color=="Violeta"){
        cadena5 ="±0.10%";
        Bandas5e.setBackground(violeta);
        }  
        if(color=="Gris"){
        cadena5 ="±0.05%";
        Bandas5e.setBackground(Color.GRAY);
        }
        if(color=="Blanco"){
        Principal.setText("Color no valido, eliga otro");
        }
        if(color=="Oro"){
        cadena5 ="±5%";
        Bandas5e.setBackground(oro);
        }
        if(color=="Plata"){
        cadena5 ="±0.5%";
        Bandas5e.setBackground(plata);
        }  
 
    }//GEN-LAST:event_Bandas5eActionPerformed

    private void Bandas6dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bandas6dActionPerformed
        String color = ColoresSelec.getSelectedItem().toString();
        if(color=="Negro"){
        cadena4 = "x 10 ^(0)";
        Bandas6d.setBackground(Color.BLACK);
        }
        if(color=="Cafe"){
        cadena4 = "x 10 ^(1)";
        Bandas6d.setBackground(cafe);
        }
        if(color=="Rojo"){
        cadena4 = "x 10 ^(2)";
        Bandas6d.setBackground(Color.RED);
        }
        if(color=="Naranja"){
        cadena4 = "x 10 ^(3)";
        Bandas6d.setBackground(Color.ORANGE);
        }
        if(color=="Amarillo"){
        cadena4 = "x 10 ^(4)";
        Bandas6d.setBackground(Color.YELLOW);
        }
        if(color=="Verde"){
        cadena4 = "x 10 ^(5)";
        Bandas6d.setBackground(Color.GREEN);
        }
        if(color=="Azul"){
        cadena4 = "x 10 ^(6)";
        Bandas6d.setBackground(Color.BLUE);
        }
        if(color=="Violeta"){
        cadena4 = "x 10 ^(7)";
        Bandas6d.setBackground(violeta);
        }
        if(color=="Gris"){
        cadena4 = "x 10 ^(8)";
        Bandas6d.setBackground(Color.GRAY);
        }
        if(color=="Blanco"){
        cadena4 = "x 10 ^(9)";
        Bandas6d.setBackground(Color.WHITE);
        }
        if(color=="Oro"){
        cadena4 ="x 10 ^(-1)";
        Bandas6d.setBackground(oro);
        }
        if(color=="Plata"){
        cadena4 ="x 10 ^(-2)";
        Bandas6d.setBackground(plata);
        }
    }//GEN-LAST:event_Bandas6dActionPerformed

    private void Bandas5dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bandas5dActionPerformed
        String color = ColoresSelec.getSelectedItem().toString();
        if(color=="Negro"){
        cadena4 = "x 10 ^(0)";
        Bandas5d.setBackground(Color.BLACK);
        }
        if(color=="Cafe"){
        cadena4 = "x 10 ^(1)";
        Bandas5d.setBackground(cafe);
        }
        if(color=="Rojo"){
        cadena4 = "x 10 ^(2)";
        Bandas5d.setBackground(Color.RED);
        }
        if(color=="Naranja"){
        cadena4 = "x 10 ^(3)";
        Bandas5d.setBackground(Color.ORANGE);
        }
        if(color=="Amarillo"){
        cadena4 = "x 10 ^(4)";
        Bandas5d.setBackground(Color.YELLOW);
        }
        if(color=="Verde"){
        cadena4 = "x 10 ^(5)";
        Bandas5d.setBackground(Color.GREEN);
        }
        if(color=="Azul"){
        cadena4 = "x 10 ^(6)";
        Bandas5d.setBackground(Color.BLUE);
        }
        if(color=="Violeta"){
        cadena4 = "x 10 ^(7)";
        Bandas5d.setBackground(violeta);
        }
        if(color=="Gris"){
        cadena4 = "x 10 ^(8)";
        Bandas5d.setBackground(Color.GRAY);
        }
        if(color=="Blanco"){
        cadena4 = "x 10 ^(9)";
        Bandas5d.setBackground(Color.WHITE);
        }
        if(color=="Oro"){
        cadena4 ="x 10 ^(-1)";
        Bandas5d.setBackground(oro);
        }
        if(color=="Plata"){
        cadena4 ="x 10 ^(-2)";
        Bandas5d.setBackground(plata);
        }

    }//GEN-LAST:event_Bandas5dActionPerformed

    private void Bandas6aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bandas6aActionPerformed
        String color = ColoresSelec.getSelectedItem().toString();
        if(color=="Negro"){
        cadena1 ="0";
        Bandas6a.setBackground(Color.BLACK);
        }
        if(color=="Cafe"){
        cadena1 = "1";
        Bandas6a.setBackground(cafe);
        }
        if(color=="Rojo"){
        cadena1= "2";
        Bandas6a.setBackground(Color.RED);
        }
        if(color=="Naranja"){
        cadena1 = "3";
        Bandas6a.setBackground(Color.ORANGE);
        }
        if(color=="Amarillo"){
        cadena1= "4";
        Bandas6a.setBackground(Color.YELLOW);
        }
        if(color=="Verde"){
        cadena1 = "5";
        Bandas6a.setBackground(Color.GREEN);
        }
        if(color=="Azul"){
        cadena1 = "6";
        Bandas6a.setBackground(Color.BLUE);
        }
        if(color=="Violeta"){
        cadena1 = "7";
        Bandas6a.setBackground(violeta);
        }
        if(color=="Gris"){
        cadena1 = "8";
        Bandas6a.setBackground(Color.GRAY);
        }
        if(color=="Blanco"){
        cadena1 = "9";
        Bandas6a.setBackground(Color.WHITE);
        }
        if(color=="Oro")
        {
           Principal.setText("Color no valido, eliga otro");
        }
        if (color=="Plata"){
            Principal.setText("Color no valido, eliga otro");
        }

    }//GEN-LAST:event_Bandas6aActionPerformed

    private void Bandas6bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bandas6bActionPerformed
        String color = ColoresSelec.getSelectedItem().toString();
        if(color=="Negro"){
        cadena2 = "0";
        Bandas6b.setBackground(Color.BLACK);
        }
        if(color=="Cafe"){
        cadena2 = "1";
        Bandas6b.setBackground(cafe);
        }
        if(color=="Rojo"){
        cadena2 = "2";
        Bandas6b.setBackground(Color.RED);
        }
        if(color=="Naranja"){
        cadena2 = "3";
        Bandas6b.setBackground(Color.ORANGE);
        }
        if(color=="Amarillo"){
        cadena2 = "4";
        Bandas6b.setBackground(Color.YELLOW);
        }
        if(color=="Verde"){
        cadena2 = "5";
        Bandas6b.setBackground(Color.GREEN);
        }
        if(color=="Azul"){
        cadena2 = "6";
        Bandas6b.setBackground(Color.BLUE);
        }
        if(color=="Violeta"){
        cadena2 = "7";
        Bandas6b.setBackground(violeta);
        }
        if(color=="Gris"){
        cadena2 = "8";
        Bandas6b.setBackground(Color.GRAY);
        }
        if(color=="Blanco"){
        cadena2 = "9";
        Bandas6b.setBackground(Color.WHITE);
        }
        if(color=="Oro"){
        Principal.setText("Color no valido, eliga otro");
        }
        if(color=="Plata"){
        Principal.setText("Color no valido, eliga otro");
        }

    }//GEN-LAST:event_Bandas6bActionPerformed

    private void Bandas6fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bandas6fActionPerformed
          String color = ColoresSelec.getSelectedItem().toString();
    if(color=="Negro"){
    Principal.setText("Color no valido, eliga otro");
    }
    if (color=="Cafe"){
    cadena6="100 PPM/C";
    Bandas6f.setBackground(cafe);
    }
    if(color=="Rojo"){
    cadena6="50 PPM/C";
    Bandas6f.setBackground(Color.RED);
    }
    if(color=="Naranja"){
    cadena6="15 PPM/C";
    Bandas6f.setBackground(Color.ORANGE);
    }
    if(color=="Amarillo"){
    Principal.setText("Color no valido, eliga otro");
    }
    if(color=="Verde"){
    Principal.setText("Color no valido, eliga otro");
    }
    if(color=="Azul"){
    cadena6="10 PPM/C";
    Bandas6f.setBackground(Color.BLUE);
    }
    if(color=="Violeta"){
    cadena6="5 PPM/C";
    Bandas6f.setBackground(violeta);
    }
    if(color=="Gris"){
    Principal.setText("Color no valido, eliga otro");
    }
    if(color=="Blanco"){
    Principal.setText("Color no valido, eliga otro");
    }
    if(color=="Oro"){
    Principal.setText("Color no valido, eliga otro");
    }
        if(color=="Plata"){
    Principal.setText("Color no valido, eliga otro");
    }
    
    
    
    }//GEN-LAST:event_Bandas6fActionPerformed

    private void Bandas6eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bandas6eActionPerformed
        String color = ColoresSelec.getSelectedItem().toString();
        if(color=="Negro"){
            Principal.setText("Color no valido, eliga otro");
        }
        if(color=="Cafe"){
        cadena5 ="±1%";
        Bandas6e.setBackground(cafe);
        }
        if(color=="Rojo"){
        cadena5 ="±2%";
        Bandas6e.setBackground(Color.RED);
        }
        if(color=="Naranja"){
        Principal.setText("Color no valido, eliga otro");
        }
        if(color=="Amarillo"){
        Principal.setText("Color no valido, eliga otro");
        }
        if(color=="Verde"){
        cadena5 ="±0.5%";
        Bandas6e.setBackground(Color.GREEN);
        }   
        if(color=="Azul"){
        cadena5 ="±0.25%";
        Bandas6e.setBackground(Color.BLUE);
        }  
        if(color=="Violeta"){
        cadena5 ="±0.10%";
        Bandas6e.setBackground(violeta);
        }  
        if(color=="Gris"){
        cadena5 ="±0.05%";
        Bandas6e.setBackground(Color.GRAY);
        }
        if(color=="Blanco"){
        Principal.setText("Color no valido, eliga otro");
        }
        if(color=="Oro"){
        cadena5 ="±5%";
        Bandas6e.setBackground(oro);
        }
        if(color=="Plata"){
        cadena5 ="±0.5%";
        Bandas6e.setBackground(plata);
        }  

    }//GEN-LAST:event_Bandas6eActionPerformed

    private void Bandas6cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bandas6cActionPerformed
        String color = ColoresSelec.getSelectedItem().toString();
        if(color=="Negro"){
        cadena3 = "0";
        Bandas6c.setBackground(Color.BLACK);
        }
        if(color=="Cafe"){
        cadena3 = "1";
        Bandas6c.setBackground(cafe);
        }
        if(color=="Rojo"){
        cadena3 = "2";
        Bandas6c.setBackground(Color.RED);
        }
        if(color=="Naranja"){
        cadena3 = "3";
        Bandas6c.setBackground(Color.ORANGE);
        }
        if(color=="Amarillo"){
        cadena3 = "4";
        Bandas6c.setBackground(Color.YELLOW);
        }
        if(color=="Verde"){
        cadena3 = "5";
        Bandas6c.setBackground(Color.GREEN);
        }
        if(color=="Azul"){
        cadena3 = "6";
        Bandas6c.setBackground(Color.BLUE);
        }
        if(color=="Violeta"){
        cadena3 = "7";
        Bandas6c.setBackground(violeta);
        }
        if(color=="Gris"){
        cadena3 = "8";
        Bandas6c.setBackground(Color.GRAY);
        }
        if(color=="Blanco"){
        cadena3 = "9";
        Bandas6c.setBackground(Color.WHITE);
        }
        if(color=="Oro"){
        Principal.setText("Color no valido, eliga otro");
        }
        if(color=="Plata"){
        Principal.setText("Color no valido, eliga otro");
        }
    }//GEN-LAST:event_Bandas6cActionPerformed

    private void Pantalla2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pantalla2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pantalla2ActionPerformed

    private void Pantalla3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pantalla3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pantalla3ActionPerformed

    private void Calcular5BandasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calcular5BandasActionPerformed
     cad1= Pantalla2.getText();
      int n;
       Color cafe=new Color(45, 25, 13);  //Creación del color café
       Color violeta=new Color(128, 0, 128);  // Creación del color violeta
       Color oro=new Color(100, 75, 0);     //Creación del color oro
       Color plata=new Color(54, 58, 59);     //Creación del color oro
       for (n=0; n<=2; n++) {
        char c = cad1.charAt (n);
        if (n==0){
        if(c=='0'){
        Bandas5a.setBackground(Color.BLACK);
        }
        if(c=='1'){       
    
        Bandas5a.setBackground(cafe);
        Bandas5a.setOpaque(true);
        }
        if (c=='2'){
        Bandas5a.setBackground(Color.RED);
        }
        if(c=='3'){
        Bandas5a.setBackground(Color.ORANGE);
        }
        if(c=='4'){
        Bandas5a.setBackground(Color.YELLOW);
        }
        if(c=='5'){
        Bandas5a.setBackground(Color.GREEN);    
        }
        if(c=='6'){
        Bandas5a.setBackground(Color.BLUE);    
        }
        if(c=='7'){
        Bandas5a.setBackground(violeta);
        Bandas5a.setOpaque(true);
        }
        if(c=='8'){
        Bandas5a.setBackground(Color.GRAY);
        }
        if(c=='9'){
        Bandas5a.setBackground(Color.WHITE);  
        }
        
        }
        if (n==1){
        if(c=='0'){
        Bandas5b.setBackground(Color.BLACK);
        }
        if(c=='1'){       
    
        Bandas5b.setBackground(cafe);
        Bandas5b.setOpaque(true);
        }
        if (c=='2'){
        Bandas5b.setBackground(Color.RED);
        }
        if(c=='3'){
        Bandas5b.setBackground(Color.ORANGE);
        }
        if(c=='4'){
        Bandas5b.setBackground(Color.YELLOW);
        }
        if(c=='5'){
        Bandas5b.setBackground(Color.GREEN);    
        }
        if(c=='6'){
        Bandas5b.setBackground(Color.BLUE);    
        }
        if(c=='7'){
        Bandas5b.setBackground(violeta);
        Bandas5b.setOpaque(true);
        }
        if(c=='8'){
        Bandas5b.setBackground(Color.GRAY);
        }
        if(c=='9'){
        Bandas5b.setBackground(Color.WHITE);  
        }        
        }
        if (n==2){
        if(c=='0'){
        Bandas5c.setBackground(Color.BLACK);
        }
        if(c=='1'){       
    
        Bandas5c.setBackground(cafe);
        Bandas5c.setOpaque(true);
        }
        if (c=='2'){
        Bandas5c.setBackground(Color.RED);
        }
        if(c=='3'){
        Bandas5c.setBackground(Color.ORANGE);
        }
        if(c=='4'){
        Bandas5c.setBackground(Color.YELLOW);
        }
        if(c=='5'){
        Bandas5c.setBackground(Color.GREEN);    
        }
        if(c=='6'){
        Bandas5c.setBackground(Color.BLUE);    
        }
        if(c=='7'){
        Bandas5c.setBackground(violeta);
        Bandas5c.setOpaque(true);
        }
        if(c=='8'){
        Bandas5c.setBackground(Color.GRAY);
        }
        if(c=='9'){
        Bandas5c.setBackground(Color.WHITE);  
        }
        }
       }
              // CASO Cuarta Banda
      String multiplicador2 = Multi2.getSelectedItem().toString();
      if(multiplicador2=="x 10 ^ (0)"){
      Bandas5d.setBackground(Color.BLACK);
      }
      if(multiplicador2=="x 10 ^ (1)"){
      Bandas5d.setBackground(cafe);
      Bandas5d.setOpaque(true);
      }
      if(multiplicador2=="x 10 ^ (2)"){
      Bandas5d.setBackground(Color.RED);
      }
      if(multiplicador2=="x 10 ^ (3)"){
      Bandas5d.setBackground(Color.ORANGE);
      }
      if(multiplicador2=="x 10 ^ (4)"){
      Bandas5d.setBackground(Color.YELLOW);
      }
      if(multiplicador2=="x 10 ^ (5)"){
      Bandas5d.setBackground(Color.GREEN);
      }
      if(multiplicador2=="x 10 ^ (6)"){
      Bandas5d.setBackground(Color.BLUE);
      }
      if(multiplicador2=="x 10 ^ (7)"){
      Bandas5d.setBackground(violeta);
      Bandas5d.setOpaque(true);
      }
      if(multiplicador2=="x 10 ^ (8)"){
      Bandas5d.setBackground(Color.GRAY);
      }
      if(multiplicador2=="x 10 ^ (9)"){
      Bandas5d.setBackground(Color.WHITE);
      }
      if(multiplicador2=="x 10 ^ (-1)"){
      Bandas5d.setBackground(oro);
      Bandas5d.setOpaque(true);
      }
      if(multiplicador2=="x 10 ^ (-2)"){
      Bandas5d.setBackground(plata);
      Bandas5d.setOpaque(true);
      }
          //CASO Quinta Banda
     String tole = Tolerancia2.getSelectedItem().toString();
     if(tole=="±1%"){
     Bandas5e.setBackground(cafe);
     Bandas5e.setOpaque(true);}
     if(tole=="±2%"){
     Bandas5e.setBackground(Color.RED);
     }
     if(tole=="±0.5%"){
     Bandas5e.setBackground(Color.GREEN);
     }
     if(tole=="±0.25%"){
     Bandas5e.setBackground(Color.BLUE);
     }
     if(tole=="±0.10%"){
     Bandas5e.setBackground(violeta);
     Bandas5e.setOpaque(true);
     }
     if(tole=="±0.05%"){
     Bandas5e.setBackground(Color.GRAY);
     }
     if(tole=="±5%"){
     Bandas5e.setBackground(oro);
     Bandas5e.setOpaque(true);
     }
     if(tole=="±10%"){
     Bandas5e.setBackground(plata);
     Bandas5e.setOpaque(true);
     }
    }//GEN-LAST:event_Calcular5BandasActionPerformed

    private void Multi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Multi3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Multi3ActionPerformed

    private void Multi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Multi1ActionPerformed
        
        
    }//GEN-LAST:event_Multi1ActionPerformed

    private void Multi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Multi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Multi2ActionPerformed

    private void Calcular6BandasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calcular6BandasActionPerformed
    cad1= Pantalla2.getText();
      int n;
       Color cafe=new Color(45, 25, 13);  //Creación del color café
       Color violeta=new Color(128, 0, 128);  // Creación del color violeta
       Color oro=new Color(100, 75, 0);     //Creación del color oro
       Color plata=new Color(54, 58, 59);     //Creación del color oro
       for (n=0; n<=2; n++) {
        char c = cad1.charAt (n);
        if (n==0){    //PRIMERA BANDA
        if(c=='0'){
        Bandas6a.setBackground(Color.BLACK);
        }
        if(c=='1'){       
    
        Bandas6a.setBackground(cafe);
        Bandas6a.setOpaque(true);
        }
        if (c=='2'){
        Bandas6a.setBackground(Color.RED);
        }
        if(c=='3'){
        Bandas6a.setBackground(Color.ORANGE);
        }
        if(c=='4'){
        Bandas6a.setBackground(Color.YELLOW);
        }
        if(c=='5'){
        Bandas6a.setBackground(Color.GREEN);    
        }
        if(c=='6'){
        Bandas6a.setBackground(Color.BLUE);    
        }
        if(c=='7'){
        Bandas6a.setBackground(violeta);
        Bandas6a.setOpaque(true);
        }
        if(c=='8'){
        Bandas6a.setBackground(Color.GRAY);
        }
        if(c=='9'){
        Bandas6a.setBackground(Color.WHITE);  
        }
        
        }
        if (n==1){
        if(c=='0'){
        Bandas6b.setBackground(Color.BLACK);
        }
        if(c=='1'){       
    
        Bandas6b.setBackground(cafe);
        Bandas6b.setOpaque(true);
        }
        if (c=='2'){
        Bandas6b.setBackground(Color.RED);
        }
        if(c=='3'){
        Bandas6b.setBackground(Color.ORANGE);
        }
        if(c=='4'){
        Bandas6b.setBackground(Color.YELLOW);
        }
        if(c=='5'){
        Bandas6b.setBackground(Color.GREEN);    
        }
        if(c=='6'){
        Bandas5b.setBackground(Color.BLUE);    
        }
        if(c=='7'){
        Bandas6b.setBackground(violeta);
        Bandas6b.setOpaque(true);
        }
        if(c=='8'){
        Bandas6b.setBackground(Color.GRAY);
        }
        if(c=='9'){
        Bandas6b.setBackground(Color.WHITE);  
        }        
        }
        if (n==2){
        if(c=='0'){
        Bandas6c.setBackground(Color.BLACK);
        }
        if(c=='1'){       
    
        Bandas6c.setBackground(cafe);
        Bandas6c.setOpaque(true);
        }
        if (c=='2'){
        Bandas6c.setBackground(Color.RED);
        }
        if(c=='3'){
        Bandas6c.setBackground(Color.ORANGE);
        }
        if(c=='4'){
        Bandas6c.setBackground(Color.YELLOW);
        }
        if(c=='5'){
        Bandas6c.setBackground(Color.GREEN);    
        }
        if(c=='6'){
        Bandas6c.setBackground(Color.BLUE);    
        }
        if(c=='7'){
        Bandas6c.setBackground(violeta);
        Bandas6c.setOpaque(true);
        }
        if(c=='8'){
        Bandas6c.setBackground(Color.GRAY);
        }
        if(c=='9'){
        Bandas6c.setBackground(Color.WHITE);  
        }
        }       
       }
       String multiplicador3 = Multi3.getSelectedItem().toString();
      if(multiplicador3=="x 10 ^ (0)"){
      Bandas6d.setBackground(Color.BLACK);
      }
      if(multiplicador3=="x 10 ^ (1)"){
      Bandas6d.setBackground(cafe);
      Bandas6d.setOpaque(true);
      }
      if(multiplicador3=="x 10 ^ (2)"){
      Bandas6d.setBackground(Color.RED);
      }
      if(multiplicador3=="x 10 ^ (3)"){
      Bandas6d.setBackground(Color.ORANGE);
      }
      if(multiplicador3=="x 10 ^ (4)"){
      Bandas6d.setBackground(Color.YELLOW);
      }
      if(multiplicador3=="x 10 ^ (5)"){
      Bandas6d.setBackground(Color.GREEN);
      }
      if(multiplicador3=="x 10 ^ (6)"){
      Bandas6d.setBackground(Color.BLUE);
      }
      if(multiplicador3=="x 10 ^ (7)"){
      Bandas6d.setBackground(violeta);
      Bandas6d.setOpaque(true);
      }
      if(multiplicador3=="x 10 ^ (8)"){
      Bandas6d.setBackground(Color.GRAY);
      }
      if(multiplicador3=="x 10 ^ (9)"){
      Bandas6d.setBackground(Color.WHITE);
      }
      if(multiplicador3=="x 10 ^ (-1)"){
      Bandas6d.setBackground(oro);
      Bandas6d.setOpaque(true);
      }
      if(multiplicador3=="x 10 ^ (-2)"){
      Bandas6d.setBackground(plata);
      Bandas6d.setOpaque(true);
      }
     String tole = Tolerancia3.getSelectedItem().toString();
     if(tole=="±1%"){
     Bandas6e.setBackground(cafe);
     Bandas6e.setOpaque(true);}
     if(tole=="±2%"){
     Bandas6e.setBackground(Color.RED);
     }
     if(tole=="±0.5%"){
     Bandas6e.setBackground(Color.GREEN);
     }
     if(tole=="±0.25%"){
     Bandas6e.setBackground(Color.BLUE);
     }
     if(tole=="±0.10%"){
     Bandas6e.setBackground(violeta);
     Bandas6e.setOpaque(true);
     }
     if(tole=="±0.05%"){
     Bandas6e.setBackground(Color.GRAY);
     }
     if(tole=="±5%"){
     Bandas6e.setBackground(oro);
     Bandas6e.setOpaque(true);
     }
     if(tole=="±10%"){
     Bandas6e.setBackground(plata);
     Bandas6e.setOpaque(true);
     }
      String temp = Temperatura.getSelectedItem().toString();
      if(temp=="100 PPM/C"){
      Bandas6f.setBackground(cafe);
      }
      if(temp=="50 PPM/C"){
      Bandas6f.setBackground(Color.RED);
      }
      if(temp=="15 PPM/C"){
          Bandas6f.setBackground(Color.ORANGE);
      }
      if(temp=="10 PPM/C"){
          Bandas6f.setBackground(Color.BLUE);
      }
      if(temp=="5 PPM/C"){
          Bandas6f.setBackground(violeta);
      }
       
    }//GEN-LAST:event_Calcular6BandasActionPerformed

    private void TemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemperaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TemperaturaActionPerformed

    private void Bandas4aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bandas4aActionPerformed
        
        String color = ColoresSelec.getSelectedItem().toString();
        if(color=="Negro"){
        cadena1 ="0";
        Bandas4a.setBackground(Color.BLACK);
        }
        if(color=="Cafe"){
        cadena1 = "1";
        Bandas4a.setBackground(cafe);
        }
        if(color=="Rojo"){
        cadena1= "2";
        Bandas4a.setBackground(Color.RED);
        }
        if(color=="Naranja"){
        cadena1 = "3";
        Bandas4a.setBackground(Color.ORANGE);
        }
        if(color=="Amarillo"){
        cadena1= "4";
        Bandas4a.setBackground(Color.YELLOW);
        }
        if(color=="Verde"){
        cadena1 = "5";
        Bandas4a.setBackground(Color.GREEN);
        }
        if(color=="Azul"){
        cadena1 = "6";
        Bandas4a.setBackground(Color.BLUE);
        }
        if(color=="Violeta"){
        cadena1 = "7";
        Bandas4a.setBackground(violeta);
        }
        if(color=="Gris"){
        cadena1 = "8";
        Bandas4a.setBackground(Color.GRAY);
        }
        if(color=="Blanco"){
        cadena1 = "9";
        Bandas4a.setBackground(Color.WHITE);
        }
        if(color=="Oro")
        {
           Principal.setText("Color no valido, eliga otro");
        }
        if (color=="Plata"){
            Principal.setText("Color no valido, eliga otro");
        }
    }//GEN-LAST:event_Bandas4aActionPerformed

    private void ImpCad6BandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImpCad6BandActionPerformed
     Principal.setText(cadena1+cadena2+cadena3+" "+cadena4+" "+cadena5+" "+cadena6);
    }//GEN-LAST:event_ImpCad6BandActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void Bandas4bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bandas4bActionPerformed
        String color = ColoresSelec.getSelectedItem().toString();
        if(color=="Negro"){
        cadena2 = "0";
        Bandas4b.setBackground(Color.BLACK);
        }
        if(color=="Cafe"){
        cadena2 = "1";
        Bandas4b.setBackground(cafe);
        }
        if(color=="Rojo"){
        cadena2 = "2";
        Bandas4b.setBackground(Color.RED);
        }
        if(color=="Naranja"){
        cadena2 = "3";
        Bandas4b.setBackground(Color.ORANGE);
        }
        if(color=="Amarillo"){
        cadena2 = "4";
        Bandas4b.setBackground(Color.YELLOW);
        }
        if(color=="Verde"){
        cadena2 = "5";
        Bandas4b.setBackground(Color.GREEN);
        }
        if(color=="Azul"){
        cadena2 = "6";
        Bandas4b.setBackground(Color.BLUE);
        }
        if(color=="Violeta"){
        cadena2 = "7";
        Bandas4b.setBackground(violeta);
        }
        if(color=="Gris"){
        cadena2 = "8";
        Bandas4b.setBackground(Color.GRAY);
        }
        if(color=="Blanco"){
        cadena2 = "9";
        Bandas4b.setBackground(Color.WHITE);
        }
        if(color=="Oro"){
        Principal.setText("Color no valido, eliga otro");
        }
        if(color=="Plata"){
        Principal.setText("Color no valido, eliga otro");
        }
        
    }//GEN-LAST:event_Bandas4bActionPerformed

    private void Bandas4cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bandas4cActionPerformed
        String color = ColoresSelec.getSelectedItem().toString();
        if(color=="Negro"){
        cadena3 = "x 10 ^(0)";
        Bandas4c.setBackground(Color.BLACK);
        }
        if(color=="Cafe"){
        cadena3 = "x 10 ^(1)";
        Bandas4c.setBackground(cafe);
        }
        if(color=="Rojo"){
        cadena3 = "x 10 ^(2)";
        Bandas4c.setBackground(Color.RED);
        }
        if(color=="Naranja"){
        cadena3 = "x 10 ^(3)";
        Bandas4c.setBackground(Color.ORANGE);
        }
        if(color=="Amarillo"){
        cadena3 = "x 10 ^(4)";
        Bandas4c.setBackground(Color.YELLOW);
        }
        if(color=="Verde"){
        cadena3 = "x 10 ^(5)";
        Bandas4c.setBackground(Color.GREEN);
        }
        if(color=="Azul"){
        cadena3 = "x 10 ^(6)";
        Bandas4c.setBackground(Color.BLUE);
        }
        if(color=="Violeta"){
        cadena3 = "x 10 ^(7)";
        Bandas4c.setBackground(violeta);
        }
        if(color=="Gris"){
        cadena3 = "x 10 ^(8)";
        Bandas4c.setBackground(Color.GRAY);
        }
        if(color=="Blanco"){
        cadena3 = "x 10 ^(9)";
        Bandas4c.setBackground(Color.WHITE);
        }
        if(color=="Oro"){
        cadena3 ="x 10 ^(-1)";
        Bandas4c.setBackground(oro);
        }
        if(color=="Plata"){
        cadena3 ="x 10 ^(-2)";
        Bandas4c.setBackground(plata);
        }
    }//GEN-LAST:event_Bandas4cActionPerformed

    private void Bandas4dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bandas4dActionPerformed
        String color = ColoresSelec.getSelectedItem().toString();
        if(color=="Negro"){
            Principal.setText("Color no valido, eliga otro");
        }
        if(color=="Cafe"){
        cadena4 ="±1%";
        Bandas4d.setBackground(cafe);
        }
        if(color=="Rojo"){
        cadena4 ="±2%";
        Bandas4d.setBackground(Color.RED);
        }
        if(color=="Naranja"){
        Principal.setText("Color no valido, eliga otro");
        }
        if(color=="Amarillo"){
        Principal.setText("Color no valido, eliga otro");
        }
        if(color=="Verde"){
        cadena4 ="±0.5%";
        Bandas4d.setBackground(Color.GREEN);
        }   
        if(color=="Azul"){
        cadena4 ="±0.25%";
        Bandas4d.setBackground(Color.BLUE);
        }  
        if(color=="Violeta"){
        cadena4 ="±0.10%";
        Bandas4d.setBackground(violeta);
        }  
        if(color=="Gris"){
        cadena4 ="±0.05%";
        Bandas4d.setBackground(Color.GRAY);
        }
        if(color=="Blanco"){
        Principal.setText("Color no valido, eliga otro");
        }
        if(color=="Oro"){
        cadena4 ="±5%";
        Bandas4d.setBackground(oro);
        }
        if(color=="Plata"){
        cadena4 ="±0.5%";
        Bandas4d.setBackground(plata);
        }  
    }//GEN-LAST:event_Bandas4dActionPerformed

    private void ImpCad4BandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImpCad4BandActionPerformed
        Principal.setText(cadena1+cadena2+" "+cadena3+" "+cadena4);
    }//GEN-LAST:event_ImpCad4BandActionPerformed

    private void ImpCad5BandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImpCad5BandActionPerformed
        Principal.setText(cadena1+" "+cadena2+cadena3+" "+cadena4+" "+cadena5);
    }//GEN-LAST:event_ImpCad5BandActionPerformed

    private void Bandas5aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bandas5aActionPerformed
        String color = ColoresSelec.getSelectedItem().toString();
        if(color=="Negro"){
        cadena1 ="0";
        Bandas5a.setBackground(Color.BLACK);
        }
        if(color=="Cafe"){
        cadena1 = "1";
        Bandas5a.setBackground(cafe);
        }
        if(color=="Rojo"){
        cadena1= "2";
        Bandas5a.setBackground(Color.RED);
        }
        if(color=="Naranja"){
        cadena1 = "3";
        Bandas5a.setBackground(Color.ORANGE);
        }
        if(color=="Amarillo"){
        cadena1= "4";
        Bandas5a.setBackground(Color.YELLOW);
        }
        if(color=="Verde"){
        cadena1 = "5";
        Bandas5a.setBackground(Color.GREEN);
        }
        if(color=="Azul"){
        cadena1 = "6";
        Bandas5a.setBackground(Color.BLUE);
        }
        if(color=="Violeta"){
        cadena1 = "7";
        Bandas5a.setBackground(violeta);
        }
        if(color=="Gris"){
        cadena1 = "8";
        Bandas5a.setBackground(Color.GRAY);
        }
        if(color=="Blanco"){
        cadena1 = "9";
        Bandas5a.setBackground(Color.WHITE);
        }
        if(color=="Oro")
        {
           Principal.setText("Color no valido, eliga otro");
        }
        if (color=="Plata"){
            Principal.setText("Color no valido, eliga otro");
        }
    }//GEN-LAST:event_Bandas5aActionPerformed

    private void Bandas5bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bandas5bActionPerformed
        String color = ColoresSelec.getSelectedItem().toString();
        if(color=="Negro"){
        cadena2 = "0";
        Bandas5b.setBackground(Color.BLACK);
        }
        if(color=="Cafe"){
        cadena2 = "1";
        Bandas5b.setBackground(cafe);
        }
        if(color=="Rojo"){
        cadena2 = "2";
        Bandas5b.setBackground(Color.RED);
        }
        if(color=="Naranja"){
        cadena2 = "3";
        Bandas5b.setBackground(Color.ORANGE);
        }
        if(color=="Amarillo"){
        cadena2 = "4";
        Bandas5b.setBackground(Color.YELLOW);
        }
        if(color=="Verde"){
        cadena2 = "5";
        Bandas5b.setBackground(Color.GREEN);
        }
        if(color=="Azul"){
        cadena2 = "6";
        Bandas5b.setBackground(Color.BLUE);
        }
        if(color=="Violeta"){
        cadena2 = "7";
        Bandas5b.setBackground(violeta);
        }
        if(color=="Gris"){
        cadena2 = "8";
        Bandas5b.setBackground(Color.GRAY);
        }
        if(color=="Blanco"){
        cadena2 = "9";
        Bandas5b.setBackground(Color.WHITE);
        }
        if(color=="Oro"){
        Principal.setText("Color no valido, eliga otro");
        }
        if(color=="Plata"){
        Principal.setText("Color no valido, eliga otro");
        }
    }//GEN-LAST:event_Bandas5bActionPerformed

    private void Bandas5cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bandas5cActionPerformed
        String color = ColoresSelec.getSelectedItem().toString();
        if(color=="Negro"){
        cadena3 = "0";
        Bandas5c.setBackground(Color.BLACK);
        }
        if(color=="Cafe"){
        cadena3 = "1";
        Bandas5c.setBackground(cafe);
        }
        if(color=="Rojo"){
        cadena3 = "2";
        Bandas5c.setBackground(Color.RED);
        }
        if(color=="Naranja"){
        cadena3 = "3";
        Bandas5c.setBackground(Color.ORANGE);
        }
        if(color=="Amarillo"){
        cadena3 = "4";
        Bandas5c.setBackground(Color.YELLOW);
        }
        if(color=="Verde"){
        cadena3 = "5";
        Bandas5c.setBackground(Color.GREEN);
        }
        if(color=="Azul"){
        cadena3 = "6";
        Bandas5c.setBackground(Color.BLUE);
        }
        if(color=="Violeta"){
        cadena3 = "7";
        Bandas5c.setBackground(violeta);
        }
        if(color=="Gris"){
        cadena3 = "8";
        Bandas5c.setBackground(Color.GRAY);
        }
        if(color=="Blanco"){
        cadena3 = "9";
        Bandas5c.setBackground(Color.WHITE);
        }
        if(color=="Oro"){
        Principal.setText("Color no valido, eliga otro");
        }
        if(color=="Plata"){
        Principal.setText("Color no valido, eliga otro");
        }
    }//GEN-LAST:event_Bandas5cActionPerformed


    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bandas4a;
    private javax.swing.JButton Bandas4b;
    private javax.swing.JButton Bandas4c;
    private javax.swing.JButton Bandas4d;
    private javax.swing.JButton Bandas5a;
    private javax.swing.JButton Bandas5b;
    private javax.swing.JButton Bandas5c;
    private javax.swing.JButton Bandas5d;
    private javax.swing.JButton Bandas5e;
    private javax.swing.JButton Bandas6a;
    private javax.swing.JButton Bandas6b;
    private javax.swing.JButton Bandas6c;
    private javax.swing.JButton Bandas6d;
    private javax.swing.JButton Bandas6e;
    private javax.swing.JButton Bandas6f;
    private javax.swing.JButton Calcular4Bandas;
    private javax.swing.JButton Calcular5Bandas;
    private javax.swing.JButton Calcular6Bandas;
    private javax.swing.JComboBox<String> ColoresSelec;
    private javax.swing.JButton ImpCad4Band;
    private javax.swing.JButton ImpCad5Band;
    private javax.swing.JButton ImpCad6Band;
    private javax.swing.JComboBox<String> Multi1;
    private javax.swing.JComboBox<String> Multi2;
    private javax.swing.JComboBox<String> Multi3;
    private javax.swing.JTextField Pantalla1;
    private javax.swing.JTextField Pantalla2;
    private javax.swing.JTextField Pantalla3;
    private javax.swing.JTextField Principal;
    private javax.swing.JComboBox<String> Temperatura;
    private javax.swing.JComboBox<String> Tolerancia1;
    private javax.swing.JComboBox<String> Tolerancia2;
    private javax.swing.JComboBox<String> Tolerancia3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
